# Generated by Django 3.0.1 on 2020-05-13 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.URLField()),
                ('author', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('time', models.IntegerField()),
                ('date', models.DateField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
