# Generated by Django 3.0.1 on 2020-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200517_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_desc',
            field=models.CharField(default='This is a default description', max_length=512),
        ),
    ]
